# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 01:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import roomie.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floorPlanPicture', models.FileField(blank=True, null=True, upload_to=roomie.models.uploadpath)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(max_length=500)),
                ('sqMeters', models.IntegerField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'Roomie Group', max_length=128)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('addRoomieGroup', models.BooleanField(default=False)),
                ('confirmGroup', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeTime', models.DateTimeField(auto_now_add=True)),
                ('relation', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Likes_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeTime', models.DateTimeField(auto_now_add=True)),
                ('relation', models.BooleanField(default=True)),
                ('followed_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_group_as_followed', to='roomie.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.TextField(blank=True, max_length=30, null=True)),
                ('joinedTime', models.DateTimeField(auto_now_add=True)),
                ('settings', models.TextField(blank=True, max_length=500, null=True)),
                ('addRoomieMember', models.BooleanField(default=False)),
                ('confirmMember', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', models.CharField(blank=True, max_length=50, null=True)),
                ('program', models.CharField(blank=True, max_length=50, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('picture', models.FileField(blank=True, null=True, upload_to=roomie.models.uploadpath)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('matchAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('address1', models.TextField(blank=True, max_length=100, null=True)),
                ('address2', models.TextField(blank=True, max_length=100, null=True)),
                ('neighborhood', models.TextField(blank=True, max_length=50, null=True)),
                ('name', models.TextField(blank=True, max_length=100, null=True)),
                ('transport', models.TextField(blank=True, max_length=500, null=True)),
                ('coordinates', models.TextField(blank=True, max_length=30, null=True)),
                ('propertyPicture', models.TextField(blank=True, max_length=500, null=True)),
                ('content_type', models.CharField(blank=True, max_length=50, null=True)),
                ('likedUsers', models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settings', models.TextField(blank=True, max_length=500, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Group')),
            ],
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes_group',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_group_as_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes_group',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Property'),
        ),
        migrations.AddField(
            model_name='likes',
            name='followed_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_as_followed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='following_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_as_following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likes',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Property'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='group', through='roomie.Membership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Property'),
        ),
        migrations.AddField(
            model_name='floorplan',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Property'),
        ),
        migrations.AddField(
            model_name='chats',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roomie.Group'),
        ),
        migrations.AddField(
            model_name='chats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
